#!/bin/zsh
pauze=$(( ( 1000000000 - $epochtime[2] + 10000000) / 1000000000. ))

while sleep $pauze; do

    date_formatted=$(date "+%a %F %H:%M:%S")

    # Returns the battery status: "Full", "Discharging", or "Charging".
    battery_status=$(< /sys/class/power_supply/BAT0/status)
    cap=$(</sys/class/power_supply/BAT0/capacity)

    if ip r show 10.10.60.0/24|grep -q .; then
        vpn='🔐'
    fi

    case $battery_status in
        'Not charging')
            bs='🔌'
            ;;
        'Discharging')
            if [[ $cap -lt 20 ]]; then
                systemctl suspend
            fi

            if [[ $cap -lt 25 ]]; then
                notify-send -t 500 -u critical '🪫Battery low!'
            fi

            if [[ $cap -lt 30 ]]; then
                bsicon='🪫'
                if ((counter-- <= 0)); then
                    counter=30
                    notify-send -t 5000 -u normal '🪫Battery low!'
                fi
            else
                bsicon='🔋'
            fi
            bs=$cap'% '$bsicon
            ;;
        'Charging')
            bs=$cap'% ⚡'
            ;;
    esac


    # Emojis and characters for the status bar
    # 💎 💻 💡 🔌 ⚡ 📁 ↑ 🐧 🪫
    echo $vpn $bs $date_formatted
done
