#!/bin/zsh
export PATH="$HOME/.bin:/usr/local/sbin:/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/games:/music/bin"
export TMP="$HOME/.local/tmp"
export TMPDIR="$TMP"

# Session
export XDG_RUNTIME_DIR=/run/user/$(id -u)

export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
export _JAVA_AWT_WM_NONREPARENTING=1

mkdir -m 700 -p $HOME/.local/log/
terminator > $HOME/.local/log/terminal.log 2>&1
