#!/bin/sh
cat > ~/.tmp/mailtmp
if spamprobe receive ~/.tmp/mailtmp | grep -q 'SPAM'; then
    spamdb -t -a $(sed -ne '/^Received: from/s|.*(\([0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\))|\1|p' ~/.tmp/mailtmp)
    whoami
fi
reformail -I 'X-localfilter: tested by localfilter' < ~/.tmp/mailtmp | /usr/local/bin/maildrop
