#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
    die "$acpi\n";
}

$status = $1;
$percent = $2;
$full_text = "$percent%";

if ($status eq 'Discharging') {
    $full_text .= ' DIS';
} elsif ($status eq 'Charging') {
    $full_text .= ' CHR';
}

$short_text = $full_text;

if ($acpi =~ /(\d\d:\d\d):/) {
    $full_text .= " ($1)";
}

# print text
print "$full_text\n";
print "$short_text\n";

# consider color and urgent flag only on discharge
if ($status eq 'Discharging') {
    if ($percent < 4) {
        system("/usr/bin/sudo /usr/sbin/s2ram");
    } elsif ($percent < 7) {
        system("notify-send -t 500 -h 'string:bgcolor:#ff0000' -h 'string:fgcolor:#000000' 'battery at '$percent'%'; SHUTTING DOWN SOON.");
        exit(33);
    } elsif ($percent < 10) {
        print "#FF0000\n";
        system("notify-send -t 500 -h 'string:bgcolor:#ff0000' -h 'string:fgcolor:#000000' 'battery at '$percent'%'");
    } elsif ($percent < 20) {
        print "#FFAE00\n";
        system("notify-send -t 500 -h 'string:bgcolor:#ffae00' -h 'string:fgcolor:#000000' 'battery at '$percent'%'");
    } elsif ($percent < 30) {
        print "#FFF600\n";
        system("notify-send -t 500 -h 'string:bgcolor:#fff600' -h 'string:fgcolor:#000000' 'battery at '$percent'%'");
    } elsif ($percent < 40) {
        print "#A8FF00\n";
        system("notify-send -t 500 -h 'string:bgcolor:#a8ff00' -h 'string:fgcolor:#000000' 'battery at '$percent'%'");
    }
}

if ($status eq 'Charging') {
    if ($percent > 80) {
#        print "#FF0000\n";
#        system("notify-send -t 500 -h 'string:bgcolor:#a8ff00' 'battery at '$percent'%'");
#        exit (33);
    } elsif ($percent < 40) {
        print "#FF0000\n";
    } elsif ($percent < 50) {
        print "#FFFF00\n";
    } elsif ($percent < 63) {
        print "#C0FF00\n";
    } elsif ($percent < 75) {
        print "#80FF00\n";
    }
}

# if ($status eq 'Full') {
#         system("notify-send -t 500 -h 'string:bgcolor:#ff0000' 'battery is FULL'");
#         exit (33);
# }

exit(0);
