#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

# Below this battery percentage I'd like to get notified.
my $range = 20;
# Below this I start nagging
my $nag = 15;
# Below this I want my system to go to sleep.
my $sleep = 5;

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;
my $rgb;
my $exit = 0;

# read the first line of the "acpi" command output
# open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
open (ACPI, "acpi -b|") or die;
$acpi = <ACPI>;
close(ACPI);
# print $acpi;
# $acpi = "Battery 0: Discharging, 39%, 03:02:26 remaining";

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
    die "$acpi\n";
}

$status = $1;
$percent = $2;
$full_text = "$percent%";

if ($status eq 'Discharging') {
    $full_text .= ' DIS';
} elsif ($status eq 'Charging') {
    $full_text .= ' CHR';
}

$short_text = $full_text;

if ($acpi =~ /(\d\d:\d\d):/) {
    $full_text .= " ($1)";
}

# print text
print "$full_text\n";
print "$short_text\n";

sub redAndGreen {
    my ($range, $percent) = @_;
    if ($percent > $range) {
        return "";
    }
    my $green = ($percent / $range) * 256;
    my $red = ($range - $percent) / $range * 256;
    $red = sprintf('%02x', $red);
    $green = sprintf('%02x', $green);
    return "#${red}${green}00";
}

$rgb = redAndGreen($range, $percent);
print "$rgb\n";

if ($status eq 'Discharging') {
    if ($percent < $range) {
        system("notify-send -t 500 -h 'string:bgcolor:$rgb' -h 'string:fgcolor:#000000' 'battery at '$percent'%'");
    }

    if ($percent < $nag) {
        $exit = 33
    };

    if ($percent < $sleep) {
        system("/usr/bin/sudo /usr/sbin/pm-suspend");
    }

    exit($exit);
}

exit(0);
