;;; resolve2.el ---

;; Copyright (C) 2006  Damien Elmes <emacs@repose.cx>

;; Author: Damien Elmes <damien@repose.cx>
;; Keywords:

;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs; see the file COPYING.  If not, write to
;; the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
;; Boston, MA 02110-1301, USA.

;;; Commentary:

;; note that the font is defined in the default face - remove the
;; family tag if you don't want to use that font

;;; Code:

(eval-when-compile    (require 'color-theme))
(defun color-theme-resolve2 ()
  "Color theme by Damien Elmes, created 2006-07-06."
  (interactive)
  (color-theme-install
   '(color-theme-resolve2
     ((background-color . "black")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "white")
      (foreground-color . "grey")
      (mouse-color . "black"))
     ((browse-kill-ring-separator-face . bold)
      (display-time-mail-face . mode-line)
      (gnus-article-button-face . bold)
      (gnus-article-mouse-face . highlight)
      (gnus-mouse-face . highlight)
      (gnus-signature-face . gnus-signature)
      (gnus-summary-selected-face . gnus-summary-selected)
      (gnus-treat-display-face . head)
      (ispell-highlight-face . highlight)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (prime-cursor-color . "Pink")
      (prime-narrow-cursor-color . "LightSkyBlue")
      (rmail-highlight-face . rmail-highlight)
      (spam-face . spam)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "black" :foreground "white smoke" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :width normal ))))
     (bg:erc-color-face0 ((t (:background "White"))))
     (bg:erc-color-face1 ((t (:background "black"))))
     (bg:erc-color-face10 ((t (:background "lightblue1"))))
     (bg:erc-color-face11 ((t (:background "cyan"))))
     (bg:erc-color-face12 ((t (:background "blue"))))
     (bg:erc-color-face13 ((t (:background "deeppink"))))
     (bg:erc-color-face14 ((t (:background "gray50"))))
     (bg:erc-color-face15 ((t (:background "gray90"))))
     (bg:erc-color-face2 ((t (:background "blue4"))))
     (bg:erc-color-face3 ((t (:background "green4"))))
     (bg:erc-color-face4 ((t (:background "red"))))
     (bg:erc-color-face5 ((t (:background "brown"))))
     (bg:erc-color-face6 ((t (:background "purple"))))
     (bg:erc-color-face7 ((t (:background "orange"))))
     (bg:erc-color-face8 ((t (:background "yellow"))))
     (bg:erc-color-face9 ((t (:background "green"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:bold t :foreground "#7777FF" :weight bold))))
     (border ((t (:background "black"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (calendar-today ((t (:underline t))))
     (change-log-acknowledgement ((t (:foreground "chocolate1"))))
     (change-log-conditionals ((t (:foreground "LightGoldenrod"))))
     (change-log-date ((t (:foreground "grey"))))
     (change-log-email ((t (:foreground "LightGoldenrod"))))
     (change-log-file ((t (:foreground "#77FFFF"))))
     (change-log-function ((t (:foreground "LightGoldenrod"))))
     (change-log-list ((t (:foreground "lightpink"))))
     (change-log-name ((t (:foreground "Aquamarine"))))
     (completion-setup-directory-face ((t (:foreground "LimeGreen"))))
     (completions-common-part ((t (:family "b&h-lucidatypewriter" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "white smoke" :background "black" :stipple nil :height 123))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cursor ((t (:background "white"))))
     (darcsum-change-line-face ((t (:background "grey25" :foreground "grey75"))))
     (darcsum-filename-face ((t (:foreground "lightblue"))))
     (darcsum-header-face ((t (:bold t :foreground "lightyellow" :weight bold))))
     (darcsum-marked-face ((t (:bold t :weight bold))))
     (darcsum-need-action-face ((t (:foreground "orange"))))
     (darcsum-need-action-marked-face ((t (:bold t :foreground "orange" :weight bold))))
     (diary ((t (:foreground "yellow1"))))
     (diary-anniversary ((t (:foreground "lightpink"))))
     (diary-button ((t (nil))))
     (diary-time ((t (:foreground "LightGoldenrod"))))
     (dired-directory ((t (:foreground "#77FFFF"))))
     (dired-flagged ((t (:bold t :weight bold :foreground "Pink"))))
     (dired-header ((t (:foreground "thistle"))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-mark ((t (:foreground "Aquamarine"))))
     (dired-marked ((t (:bold t :weight bold :foreground "Pink"))))
     (dired-symlink ((t (:foreground "lightpink"))))
     (dired-warning ((t (:foreground "#ffaaaa"))))
     (emms-browser-album-face ((t (:foreground "#aaaaff" :height 1.1 :family "Arial"))))
     (emms-browser-artist-face ((t (:foreground "#ccffcc" :underline t :height 1.3 :family "Arial"))))
     (emms-browser-track-face ((t (:foreground "#aaaaff" :height 1.0 :family "Arial"))))
     (emms-browser-year/genre-face ((t (:foreground "#ffaaaa" :underline t :height 1.6 :family "Arial"))))
     (emms-metaplaylist-mode-current-face ((t (:foreground "red2"))))
     (emms-metaplaylist-mode-face ((t (:foreground "AntiqueWhite3"))))
     (emms-playlist-selected-face ((t (:foreground "#ffaaaa"))))
     (emms-playlist-track-face ((t (:foreground "DarkSeaGreen" :family "Arial"))))
     (emms-stream-name-face ((t (:bold t :weight bold))))
     (emms-stream-url-face ((t (:foreground "LightSteelBlue"))))
     (erc-action-face ((t (:bold t :weight bold))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-command-indicator-face ((t (:bold t :weight bold))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "white"))))
     (erc-error-face ((t (:foreground "red"))))
     (erc-input-face ((t (:foreground "brown"))))
     (erc-inverse-face ((t (:background "Black" :foreground "White"))))
     (erc-nick-default-face ((t (:bold t :weight bold))))
     (erc-nick-msg-face ((t (:bold t :foreground "pink1" :weight bold))))
     (erc-notice-face ((t (:bold t :foreground "SlateBlue" :weight bold))))
     (erc-prompt-face ((t (nil))))
     (erc-underline-face ((t (:underline t))))
     (escape-glyph ((t (:foreground "cyan"))))
     (fg:erc-color-face0 ((t (:foreground "White"))))
     (fg:erc-color-face1 ((t (:foreground "black"))))
     (fg:erc-color-face10 ((t (:foreground "lightblue1"))))
     (fg:erc-color-face11 ((t (:foreground "cyan"))))
     (fg:erc-color-face12 ((t (:foreground "blue"))))
     (fg:erc-color-face13 ((t (:foreground "deeppink"))))
     (fg:erc-color-face14 ((t (:foreground "gray50"))))
     (fg:erc-color-face15 ((t (:foreground "gray90"))))
     (fg:erc-color-face2 ((t (:foreground "blue4"))))
     (fg:erc-color-face3 ((t (:foreground "green4"))))
     (fg:erc-color-face4 ((t (:foreground "red"))))
     (fg:erc-color-face5 ((t (:foreground "brown"))))
     (fg:erc-color-face6 ((t (:foreground "purple"))))
     (fg:erc-color-face7 ((t (:foreground "orange"))))
     (fg:erc-color-face8 ((t (:foreground "yellow"))))
     (fg:erc-color-face9 ((t (:foreground "green"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (find-file-root-header-face ((t (:background "red3" :foreground "white"))))
     (fixed-pitch ((t (:family "courier"))))
     (flashcard-answer-face ((t (:foreground "green"))))
     (flashcard-input-correct-face ((t (:bold t :foreground "green" :weight bold))))
     (flashcard-input-face ((t (:foreground "cyan"))))
     (flashcard-input-wrong-face ((t (:foreground "red"))))
     (flashcard-question-face ((t (:foreground "cyan"))))
     (font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-comment-delimiter-face ((t (:foreground "light steel blue"))))
     (font-lock-comment-face ((t (:foreground "light steel blue"))))
     (font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (font-lock-doc-face ((t (:foreground "white smoke"))))
     (font-lock-function-name-face ((t (:foreground "#77FFFF"))))
     (font-lock-keyword-face ((t (:foreground "lightpink"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "white"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "grey"))))
     (font-lock-type-face ((t (:foreground "thistle"))))
     (font-lock-variable-name-face ((t (:foreground "LightGoldenrod"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink" :weight bold))))
     (fringe ((t (:background "grey10"))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-strikethru ((t (:strike-through t))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t :slant italic :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic))))
     (gnus-group-mail-1 ((t (:bold t :foreground "aquamarine1" :weight bold))))
     (gnus-group-mail-1-empty ((t (:foreground "aquamarine1"))))
     (gnus-group-mail-2 ((t (:bold t :foreground "aquamarine2" :weight bold))))
     (gnus-group-mail-2-empty ((t (:foreground "aquamarine2"))))
     (gnus-group-mail-3 ((t (:bold t :foreground "aquamarine3" :weight bold))))
     (gnus-group-mail-3-empty ((t (:foreground "aquamarine3"))))
     (gnus-group-mail-low ((t (:bold t :foreground "aquamarine4" :weight bold))))
     (gnus-group-mail-low-empty ((t (:foreground "aquamarine4"))))
     (gnus-group-news-1 ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-group-news-1-empty ((t (:foreground "PaleTurquoise"))))
     (gnus-group-news-2 ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-news-2-empty ((t (:foreground "turquoise"))))
     (gnus-group-news-3 ((t (:bold t :weight bold))))
     (gnus-group-news-3-empty ((t (nil))))
     (gnus-group-news-4 ((t (:bold t :weight bold))))
     (gnus-group-news-4-empty ((t (nil))))
     (gnus-group-news-5 ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty ((t (nil))))
     (gnus-group-news-6 ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty ((t (nil))))
     (gnus-group-news-low ((t (:bold t :foreground "DarkTurquoise" :weight bold))))
     (gnus-group-news-low-empty ((t (:foreground "DarkTurquoise"))))
     (gnus-header-content ((t (:foreground "snow2" :slant normal))))
     (gnus-header-from ((t (:foreground "spring green"))))
     (gnus-header-name ((t (:foreground "white" :weight normal))))
     (gnus-header-newsgroups ((t (:italic t :foreground "yellow" :slant italic))))
     (gnus-header-subject ((t (:foreground "SeaGreen3"))))
     (gnus-signature ((t (:italic t :slant italic))))
     (gnus-splash ((t (:foreground "#888888"))))
     (gnus-summary-cancelled ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (gnus-summary-high-read ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (gnus-summary-high-ticked ((t (:bold t :foreground "pink" :weight bold))))
     (gnus-summary-high-undownloaded ((t (:bold t :foreground "LightGray" :weight bold))))
     (gnus-summary-high-unread ((t (:bold t :weight bold))))
     (gnus-summary-low-ancient ((t (:italic t :foreground "SkyBlue" :slant italic))))
     (gnus-summary-low-read ((t (:italic t :foreground "PaleGreen" :slant italic))))
     (gnus-summary-low-ticked ((t (:italic t :foreground "pink" :slant italic))))
     (gnus-summary-low-undownloaded ((t (:italic t :foreground "LightGray" :slant italic :weight normal))))
     (gnus-summary-low-unread ((t (:italic t :slant italic))))
     (gnus-summary-normal-ancient ((t (:foreground "SkyBlue"))))
     (gnus-summary-normal-read ((t (:foreground "PaleGreen"))))
     (gnus-summary-normal-ticked ((t (:bold t :foreground "pink" :weight bold))))
     (gnus-summary-normal-undownloaded ((t (:foreground "LightGray" :weight normal))))
     (gnus-summary-normal-unread ((t (nil))))
     (gnus-summary-selected ((t (:underline t))))
     (header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (nil))))
     (highlight ((t (:background "darkolivegreen"))))
     (holiday ((t (:background "chocolate4"))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (iswitchb-current-match ((t (:foreground "#77FFFF"))))
     (iswitchb-invalid-regexp ((t (:bold t :weight bold :foreground "Pink"))))
     (iswitchb-single-match ((t (:foreground "chocolate1"))))
     (iswitchb-virtual-matches ((t (:foreground "LightSteelBlue"))))
     (italic ((t (:foreground "#FFFFaa"))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (nil))))
     (message-cited-text ((t (:foreground "red"))))
     (message-header-cc ((t (:bold t :foreground "green4" :weight bold))))
     (message-header-name ((t (:foreground "DarkGreen"))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "lightblue" :slant italic :weight bold))))
     (message-header-other ((t (:foreground "#b00000"))))
     (message-header-subject ((t (:foreground "green3"))))
     (message-header-to ((t (:bold t :foreground "green2" :weight bold))))
     (message-header-xheader ((t (:foreground "blue"))))
     (message-mml ((t (:foreground "ForestGreen"))))
     (message-separator ((t (:foreground "blue3"))))
     (minibuffer-prompt ((t (:bold t :weight bold))))
     (mode-line ((t (:background "#101070" :foreground "white"))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "#202020" :foreground "white"))))
     (mouse ((t (:background "black"))))
     (next-error ((t (:background "blue3"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (prime-cand-cursor-face ((t (:background "Pink" :foreground "white"))))
     (query-replace ((t (:foreground "brown4" :background "palevioletred2"))))
     (region ((t (:background "blue3"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "SkyBlue4"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "steelblue3"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (spam ((t (:foreground "ivory2"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "helv" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (vertical-border ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "grey70"))))
     (widget-single-line-field ((t (:background "dim gray")))))))
(add-to-list 'color-themes '(my-color-theme  "resolve2" "Damien Elmes"))

(provide 'resolve2)
