#!/bin/sh
export PATH="/usr/local/bin/:/sbin:/bin:/usr/sbin:/usr/bin"
log=/var/log/authlog
daily()
{
    ex_heroes=$(sudo pfctl -t heroes -T expire 8640000 2>&1)
    if ! echo $ex_heroes | grep 0/0; then
        echo expiring heroes
        echo $ex_heroes
    fi
    ex_brutes=$(sudo pfctl -t brutes -T expire 8640000 2>&1)
    if ! echo $ex_brutes | grep 0/0; then
        echo expiring brutes
        echo $ex_brutes
    fi

    brutes=$(sudo pfctl -t brutes -T show)
    set -- $(grep "$(date '+%b %e')" $log | sed -ne '/Failed password/s|.*from \(.*\) port.*|\1|p' | sort -n | uniq -c| sort -rn| head -n 20| awk '{if ($1 > 10) print $2}')
    while [ $# -gt 0 ]; do
        if ! echo $brutes | grep -q "[[:<:]]$1[[:>:]]"; then
            echo "adding $i to the brutes"
            sudo pfctl -t brutes -T add $1
            grep $1 $log
            whois $1 |grep 'abuse'
        fi
        shift
    done
}

hourly()
{
    brutes=$(sudo pfctl -t brutes -T show)
    set -- $(grep "$(date '+%b %e %H')" $log | sed -ne '/Failed password/s|.*from \(.*\) port.*|\1|p' | sort -n | uniq -c| sort -rn| head -n 20| awk '{if ($1 > 3) print $2}')
    while [ $# -gt 0 ]; do
        if ! echo $brutes | grep -q "[[:<:]]$1[[:>:]]"; then
            echo "adding $i to the brutes"
            sudo pfctl -t brutes -T add $1
            whois $1 |grep 'abuse'
            grep $1 $log
        fi
        shift
    done

    # set -- $(grep "$(date '+%b %e %H')" $log | sed -ne '/Connection closed by/s|.*closed by \(.*\) port.*|\1|p' | sort -n | uniq -c| sort -rn| head -n 20| awk '{if ($1 > 3) print $2}')
    # while [ $# -gt 0 ]; do
    #     if ! echo $brutes | grep -q "[[:<:]]$1[[:>:]]"; then
    #         echo "adding $i to the brutes"
    #         sudo pfctl -t brutes -T add $1
    #         whois $1 |grep 'abuse'
    #         grep $1 $log
    #     fi
    #     shift
    # done

    heroes=$(sudo pfctl -t heroes -T show)
    set -- $(grep "$(date '+%b %e %H')" $log | sed -ne '/Accepted [password|publickey]/s|.*from \(.*\) port.*|\1|p' | sort -n | uniq)
    while [ $# -gt 0 ]; do
        if ! echo $heroes | grep -q "[[:<:]]$1[[:>:]]"; then
            echo "adding $i to the heroes"
            sudo pfctl -t heroes -T add $1
            grep $1 $log
        fi
        shift
    done
}

if [ "$(date '+%H')" = 0 ]; then
    daily
fi

hourly
