#!/bin/sh
ID=$(id -u)
if [ $ID -eq 0 ]; then
    echo "Don't do this!"
    exit 1
fi

socket=${TMPDIR:=~/.tmp}/emacs$ID/server
emacsclient -t --socket-name $socket "$@" -a '' || exit 1
# exec emacs "$@"
