#!/usr/bin/env zsh

# in console mode [I appears
opts=''

if pgrep -f 'emacs.*--daemon'; then
        emacsclient ${opts:=-c} --socket-name $XDG_RUNTIME_DIR/emacs/server "$@"
else
    emacs $opts "$@"
fi
