#!/bin/sh
case "$1" in
    lock)
        lockmeup &
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        systemctl suspend
        ;;
    suslock)
        lockmeup &
        sleep 1
        systemctl suspend
        ;;
    hibernate)
        lockmeup &
        sleep 1
        systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
