#!/bin/zsh
factor=10

screenshot()
{
    if [[ -S $SWAYSOCK ]]; then
        grim "$1"
    else
        scrot "$1"
    fi
}


lockmeup()
{
    if [[ -S $SWAYSOCK ]]; then
        swaylock -F -e -i "$1"
    else
        i3lock  -n -e -f -i "$1"
    fi
}

mogrifyss()
{
    ss=$(mktemp).png
    ((fdwn = 100/factor))
    ((fup = 100*factor))

    # Take a screenshot
    screenshot $ss

    # Pixellate it $factor
    mogrify -scale $fdwn% -scale $fup% $ss

    # Lock screen displaying this image.
    lockmeup $ss
    sleep 1
    rm $ss
}

safe()
{
    lockmeup ~/.config/lockmeup/safe.png
}

mordor()
{
    lockmeup ~/.config/lockmeup/mordor.jpg
}

#xset +dpms
#xset dpms 0 0 60

case $(($RANDOM % 3)) in
    0)
        safe
        ;;
    1)
        mordor
        ;;
    2)
        mogrifyss
        ;;
esac

# xset -dpms
