#!/bin/sh
tail -n3 -f /var/log/spamd | while read line; do
    ip=$(echo $line|awk '{print $NF}')
    set -- $(echo $ip| sed -e 's|\.| |g')
    revip=$4.$3.$2.$1
    if host $revip.zen.spamhaus.org|grep -q '127\.0'; then
	spamdb -t -a $ip
	echo "zen didn't like $ip"
    elif host $revip.cbl.abuseat.org | grep -q '127\.0'; then
	spamdb -t -a $ip
	echo "cbl.abuseat.org didn't like $ip"
    elif host $revip.b.barracudacentral.org | grep -q '127\.0'; then
	spamdb -t -a $ip
	echo "baracuda didn't like $ip"
    elif host $revip.bl.spamcop.net | grep -q '127\.0'; then
	spamdb -t -a $ip
	echo "spamcop didn't like $ip"
    else
	echo "$ip found to be clean."
	spamdb -a $ip
    fi
done
