#!/bin/sh
if wget "http://list.iblocklist.com/?list=bt_level1&fileformat=p2p&archiveformat=gz" -O - | gunzip -c | cut -d: -f2 > /mp3/downloads/.session/ipfilter_level1.txt.new; then
    mv /mp3/downloads/.session/ipfilter_level1.txt.new /mp3/downloads/.session/ipfilter_level1.txt
else
    echo "Blocklist update failed."
    exit 1
fi
